/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b1e7c6e6-6b75-418e-8304-f91d37eb120a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_VjWGRxhDf",
    "aws_user_pools_web_client_id": "52o56g094o3ett8dc1mel86kfb",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://zqvdyadk3rcibcj6vzgj3eh2zm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
